create table if not exists public.products (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text not null,
  source_product_id text,
  sku text,
  title text not null,
  brand text,
  category text,
  description text,
  currency text,
  source_price numeric,
  in_stock boolean not null default false,
  status text not null default 'active',
  sizes jsonb not null default '[]'::jsonb,
  images jsonb not null default '[]'::jsonb,
  raw_hash text,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, source_url)
);

create index if not exists products_source_idx on public.products(source);
create index if not exists products_brand_idx on public.products(brand);
create index if not exists products_category_idx on public.products(category);
create index if not exists products_status_idx on public.products(status);
